# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Awesome xonshrc test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'xonsh[full]'
    - name: Test xonshrc
      run: |
        pip install .
        filename=$(basename -- $(ls xontrib/*.*))
        xontrib_name="${filename%.*}"
        r=$(xonsh -c "xontrib load $xontrib_name" 2>&1)
        echo $r
        [ "$r" == "" ] && exit 0 || exit 1
